name: docker

on:
  push:

env:
  GO_VERSION: "1.20"
  CGO_ENABLED: 0
  IMAGE_REPOSITORY: sosedoff/pgweb

jobs:
  docker-build:
    name: docker images
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Configure docker build context
        uses: docker/setup-buildx-action@v2

      - name: Build no args docker images
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: pgweb:noargs
          file: Dockerfile.noargs
          platforms: linux/amd64

      - name: Build args docker images
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: pgweb:args
          file: Dockerfile.args
          platforms: linux/amd64
          build-args: |
            "CGO_ENABLED=${{ env.CGO_ENABLED }}"
